server:
  port: 8081
spring:
  application:
    name: micro-server
  redis:
    password: 123456
    host: 127.0.0.1
    port: 6379
    database: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/


